SELECT
    id,
    processor_id,
    external_merchant_id,
    merchant_code,
    legal_name,
    display_name,
    NULL as business_type,
    NULL as mcc,
    NULL as industry,
    NULL as website,
    country,
    NULL as timezone,
    NULL as support_email,
    NULL as support_phone,
    NULL as default_currency,
    NULL::TEXT[] as supported_currencies,
    NULL as settlement_currency,
    status,
    NULL as risk_profile,
    NULL as kyc_status,
    NULL::TIMESTAMP WITH TIME ZONE as kyc_verified_at,
    NULL::JSONB as metadata,
    CURRENT_TIMESTAMP as activated_at,
    CURRENT_TIMESTAMP as created_at,
    CURRENT_TIMESTAMP as updated_at
FROM {{ source('raw_data', 'merchants') }}
